### ISSUE TITLE
Mutiple Jira project

### ISSUE THREAD

**Issue by Brett-Tilney** [MarvalSoftware/MarvalSoftware.Plugins.JIRA#16]
We are looking at this for managing enhancement requests for inhouse developed applications, using the marvel ticket to review /approve,  then raising a JIRA issue in the various development streams projects. Currently it looks like you have to setup this plug to use a common JIRA project. Could we not have a way to select the project from a pre-determined list (Dictionary?)

**Comment by scpatterson47** [comment]
Hi Brett, this feature has been included in v3.0.0.1 of the JIRA plugin for MSM. We've enhanced the issue types drop-down menu to now include all of the associated JIRA projects and their individual issue types.
